backend:
  name: github
  repo: PutziSan/gatsby-netlify-cms

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - label: Featured Image
        name: thumbnail
        widget: image
        required: false
      - label: Blog post content
        name: body
        widget: markdown
        required: false